config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  resources :newsletters, only: [:create]
  resources :pages, only: [:index, :new, :create]
  resources :products, only: [:index, :show, :create] do
    resources :reviews, only: [:create, :update, :destroy ]
    member do
      post 'toggle_favorite', to: "products#toggle_favorite"
    end
  end

  resources :users, only: [:show, :update]
  resources :orders, only: [:update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create], path: 'cart'
  get 'success', to: 'charges#success_charge'
  get 'cancel', to: 'charges#cancel_charge'
end

app/views/pages/shared/_carousel.html.erb
<div id="carouselCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "carousel-homepage.jpg", class:"d-block w-100", alt: "First slide", style:"max-height: 100vh"%>
      <div class="carousel-caption d-none d-md-block">
        <h1>
          <div id="caption-title-typed">
            <span>
              Lorem ipsum dolor<br>
              sit amet<br>
              consectetur</span>
          </div>
        </h1>
        <h1 style="position: relative"><span id="title-typed"></span></h1>
        <p>
          <div id="caption-subtitle-typed">
            <span>Excepteur sint occaecat cupidatat non proident</span>
          </div>
        </p>
        <p><span id="subtitle-typed"></span></p>
        <div class="cta-btns">
          <a class="learn-cta-btn" href="/about">LEARN MORE</a>
          <a class="buy-cta-btn-background" href="/products">BUY NOW</a>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel-homepage1.jpg", class:"d-block w-100", alt: "First slide", style:"max-height: 100vh"%>
      <div class="carousel-caption d-none d-md-block">
        <h1>Sed ut<br>
          omnis iste natus<br>
          error sit</h1>
        <p>Excepteur sint occaecat cupidatat non proident</p>
        <div class="cta-btns">
          <a class="learn-cta-btn" href="/about">LEARN MORE</a>
          <a class="buy-cta-btn-background" href="/products">BUY NOW</a>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel-homepage2.jpg", class:"d-block w-100", alt: "First slide", style:"max-height: 100vh"%>
      <div class="carousel-caption d-none d-md-block">
        <h1>At vero<br>
          accusamus et<br>
          dignissimos</h1>
        <p>Excepteur sint occaecat cupidatat non proident</p>
        <div class="cta-btns">
          <a class="learn-cta-btn" href="/about">LEARN MORE</a>
          <a class="buy-cta-btn-background" href="/products">BUY NOW</a>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/shared/_cart_display.html.erb
<div>
  <% if current_user %>
    <%= link_to order_items_path(product_id: product), remote: true, method: :post do %>
      <i class="fas fa-shopping-cart"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
      <i class="fas fa-shopping-cart"></i>
    <% end %>
  <% end %>
</div>

app/views/pages/shared/_contact_form.html.erb
<h3 class="contact-section-header"><span>Ready to try it?</span> GET IN TOUCH</h3>
<%= form_for @contact, url: pages_path, remote: true  do |f| %>
  <div class= "contact-section-flex-row">
    <div class="form-input-spacing">
      <%= f.label :name %>
      <%= f.text_field  :name, required: true, class: "contact-form-text-area" %>
    </div>
    <div class="form-input-spacing">
      <%= f.label :email %>
      <%= f.text_field :email, required: true, class: "contact-form-text-area" %>
    </div>
  </div>
  <div class="contact-section-area-input">
    <%= f.label :message %>
    <%= f.text_area :message, rows: 8, cols: 59, required: true, class: "contact-form-text-area",
                            placeholder: "Send us a message"%>
  </div>
  <div class="contact-section-submit-form send-btn">
    <%= f.submit 'Contact Us', id: "submit-input", style: "border: none !important; background: none; color: white"%>
    <i class="fa fa-paper-plane replace"></i>
    <i class="fas fa-check hidden"></i>
  </div>
<% end %>

app/views/pages/shared/_favoritor.html.erb
<% if current_user %>
  <div>
    <%= link_to toggle_favorite_product_path(product), remote: true, method: :post, "data-id": "#{product.id}" do %>
      <%= render 'pages/like_button', product: product %>
    <% end %>
  </div>
<% end %>

app/views/pages/shared/_intro.html.erb
<div class="container grid-intro">
  <div class="intro-message">
    <h3>Nice to meet you</h3>
    <h2 style="text-transform: uppercase">We are <%= ENV['SHOP_NAME'] %></h2>
    <p>Duis autem vel eum iriure dolor in hendrerit vulputate molestie consequat illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option putamus parum anteposuerit formas humanitatis claram congue</p>
    <a href="/products" class="buy-cta-btn-no-background">SHOP NOW</a>
  </div>
  <div class="intro-pics">
    <div class="intro-pics-first">
      <%= image_tag "intro-pic-first.jpg", class:"d-block w-100", alt: "intro pic 1"%>
      <%= image_tag "intro-pic-first1.jpg", class:"d-block w-100", alt: "intro pic 2"%>
    </div>
    <div class="intro-pics-second">
      <%= image_tag "intro-pic-second.jpg", class:"d-block w-100", alt: "intro pic 3"%>
      <%= image_tag "intro-pic-second1.jpg", class:"d-block w-100", alt: "intro pic 4"%>
    </div>
  </div>
</div>

app/views/pages/shared/_product_display.html.erb
<div>
  <div class="product-card">
    <%= link_to product_path(product) do %>
      <div class="info-hover">
        <a href="/products/<%= product.id %>"><i class="fas fa-eye"></i></a>
        <!-- Favoritor -->
        <%= render "pages/shared/favoritor", product: product  %>
        <!-- Cart icon -->
        <%= render "pages/shared/cart_display", product: product %>
      </div>
      <%= cl_image_tag product.photos[0].key, height: 300, width: 400, crop: :fill, class: 'product-first-pic' %>
      <%= cl_image_tag product.photos[2].key, height: 300, width: 400, crop: :fill, class: 'product-second-pic' %>
      <div class="product-info">
        <h3><%= product.name %></h3>
        <div>
          <% if product.rating %>
            <% product.rating.floor.times do %>
              <i class="fas fa-star active"></i>
            <%end %>
            <% if product.rating.to_s.include?('.5') %>
              <i class="fas fa-star-half-alt active"></i>
            <% end %>
            <% (5 - product.rating.ceil).times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <% else %>
            <% 5.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <%end %>
        </div>
        <p><%= product.description %></p>
        <p><%= pretty_amount(product.price) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/shared/_product_wrapper.html.erb
<h3 class="subtitle-display-product">Discover</h3>
<h2>POPULAR ITEMS</h2>
<div class="container products-grid">
  <% delay = 0 %>
  <% @products.each do |product| %>
    <!-- Product info -->
    <div data-aos="fade-right"  data-aos-duration="1000" data-aos-delay="<%= delay > 200 ? 0 : delay == 0 ? 0 : 200 %>" >
      <% delay += 200 %>
      <div>
        <%= render "pages/shared/product_display", product: product %>
      </div>
    </div>
  <% end %>
</div>