config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  resources :newsletters, only: [:create]
  resources :pages, only: [:index, :new, :create]
  resources :products, only: [:index, :show, :create] do
    resources :reviews, only: [:create, :update, :destroy ]
    member do
      post 'toggle_favorite', to: "products#toggle_favorite"
    end
  end

  resources :users, only: [:show, :update]
  resources :orders, only: [:update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create], path: 'cart'
  get 'success', to: 'charges#success_charge'
  get 'cancel', to: 'charges#cancel_charge'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # before_action :authenticate_user!

  def new
    @user = current_user
    
    if @user
      @order = Order.where(user: @user, status: 1)[0]
      authorize @user     
      if @order 
        @cart_items = @order.order_items.order(:id) 
        @amount =  Order.update_total(@order)
        authorize @order
        return @amount
      end
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @order = Order.where(user: current_user, status: 1)[0] #created this just to overcome the Pundit auth
    @order_id = @order.id
    @order_items = OrderItem.where(order_id: @order_id)
    @hashed_order_items = @order_items.map {|el| {price: Product.find(el.product_id).stripe_price_id, quantity: el.quantity} }

    authorize @order
    session = Stripe::Checkout::Session.create({
      line_items: @hashed_order_items,
      mode: 'payment',
      success_url: ENV['DOMAIN'] + '/success',
      cancel_url: ENV['DOMAIN'] + '/cancel',
    })

    redirect_to session.url
  end

  def success_charge
    orders_controller = OrdersController.new
    @user = current_user
    @order = Order.where(user: current_user, status: 1)[0]
    authorize @order
    orders_controller.update(@user, @order)  
    
    redirect_to root_path, notice: "Thank you, your order has been made!"
  end

  def cancel_charge
    @user = current_user
    authorize @user
    redirect_to products_path, notice: "Forgot to add something to your cart? Shop around then come back to pay!"
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents, unit: "¥", precision: 0)
  end
end

app/views/charges/shared/_display_orders.html.erb
<section style="overflow-x: scroll;">
  <ul class="checkout-title">
    <li>Product</li>
    <li>Name</li>
    <li>Price</li>
    <li>Quantity</li>
    <li>Total</li>
    <li>Remove</li>
  </ul>
  <% cart_items.each do |item| %>
    <ul class="checkout-info">
      <li><%=cl_image_tag item.product.photos[0].key, height: 40, width: 40, crop: :fill %></li>
      <li><%= item.product.name %></li>
      <li><%= pretty_amount(item.product.price) %></li>
      <!-- Change quantity -->
      <li class="quantity-change" data-id=<%="#{item.product.id}"%>>
        <%= link_to order_item_path(item, operator: 'minus', "data-id": "#{item.product.id}"), remote: true, method: :patch do %>
          <button>-</button>
        <%end %>
        <%= item.quantity %>
        <%= link_to order_item_path(item, operator: 'plus', "data-id": "#{item.product.id}"), remote: true, method: :patch do %>
          <button>+</button>
        <%end %>
      </li>
      <li><%= pretty_amount(item.quantity * item.product.price)%></li>
      <li>
        <!-- Delete item -->
        <%= link_to "Remove",
            order_item_path(item, order: order, "data-id": "#{item.product.id}"),
            method: :delete, remote: true,  "data-id": "#{item.product.id}" %>
      </li>
    </ul>
  <% end %>
</section>

app/views/charges/shared/_emptycart.html.erb
<section class="container add-padding-product empty-shopping">
  <h1>Shopping Cart</h1>
  <!-- Empty cart -->
  <div class="empty-shopping-text">
    <h3>YOUR CART IS CURRENTLY EMPTY.</h3>
    <p>Continue shopping <a href="/products">here</a>.</p>
  </div>
</section>

app/views/charges/shared/_fullcart.html.erb
<!-- Info needed for the shipping -->
<article class="cart-procedure">
  <section class="steps container">
    <div class="step active-step" data-highlight="one">
      <h3>Step 1</h3>
      <p>Shipping Information</p>
    </div>
    <div class="step" data-highlight="two">
      <h3>Step 2</h3>
      <p>Billing Information</p>
    </div>
    <div class="step" data-highlight="three">
      <h3>Step 3</h3>
      <p>Checkout</p>
    </div>
  </section>
  <section class="container full-shopping">
    <!-- First step -->
    <div class="form-step step-one" data-step="one" style="padding: 0 0 24px 0;">
      <h2>Shipping Information</h2>
      <% if @user.name %>
        <!-- First step when shipping info -->
        <div class="cart-form ">
          <p id="fullname"><span>Name:</span> <%= @user.name %></p>
          <p><span> Address:</span> <%= @user.shipping_address %></p>
          <p><span> Phone number:</span> <%= @user.phone_number %></p>
          <!-- Hidden form -->
          <%= simple_form_for(@user, remote: true, method: :patch) do |f| %>
            <%if  @user.checked == 0 || !@user.checked %>
              <%= f.input_field :checked, as: :boolean, class: "hidden_form not-checked two"  %>
            <% else %>
              <%= f.input_field :checked, as: :boolean, class: "hidden_form checked two" %>
            <% end %>
            <%= f.button :submit, class: "hidden_form" %>
          <% end  %>
          <button class="next-btn go-step-two pass-data" data-key="two">Next</button>
          <button class="next-btn change-shipping-btn">Change</button>
          <div class="change-shipping-info">
            <%= simple_form_for(@user, remote: true, method: :patch) do |f| %>
              <div id="name">
                <%= f.input :name, label: 'Full name', required: true %>
              </div>
              <div id="shipping_address">
                <%= f.input :shipping_address,required: true %>
              </div>
              <div id="phone">
                <%= f.input :phone_number, required: true %>
              </div>
              <%= f.submit 'Submit', class: "next-btn" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <!-- First step when no shipping info -->
        <div class="cart-form not-filled-shipping">
          <%= simple_form_for(@user, remote: true, method: :patch) do |f| %>
            <div id="name">
              <%= f.input :name, label: 'Full name', required: true %>
            </div>
            <div id="shipping_address">
              <%= f.input :shipping_address,required: true %>
            </div>
            <div id="phone">
              <%= f.input :phone_number, required: true %>
            </div>
            <%= f.submit 'Save', class: "next-btn add-shipping-info" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- Second step -->
    <div class="form-step step-two form-hidden" data-step="two" style="padding: 0 0 24px 0;">
      <h2>Billing Information</h2>
      <div class="cart-form">
        <% if @user.shipping_address == @order.billing_address %>
          <p><span>Billing address:</span> Same as shipping address</p>
        <% else %>
          <p><span>Billing address:</span> <%= @order.billing_address %></p>
        <% end %>
        <!-- Hidden form -->
        <%= simple_form_for(@order, remote: true, method: :patch) do |f| %>
          <%if  @order.checked == 0 || !@order.checked  %>
            <%= f.input_field :checked, as: :boolean, class: "hidden_form not-checked three" %>
          <% else %>
            <%= f.input_field :checked, as: :boolean, class: "hidden_form checked three" %>
          <% end %>
          <%= f.button :submit, class: "hidden_form" %>
        <% end  %>
        <div class="d-flex">
          <button class="next-btn go-step-one" data-key="one">Previous</button>
          <button class="next-btn change-billing-btn">Change</button>
          <button class="next-btn go-step-three pass-data" data-key="three">Next</button>
        </div>
        <div class="change-billing-info">
          <%= simple_form_for(@order, remote: true, method: :patch) do |f| %>
            <div id="billing">
              <%= f.input :billing_address, required: true %>
            </div>
            <%= f.submit 'Submit', class: "next-btn" %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Third step -->
    <div class="form-step form-hidden" data-step="three" style="padding: 0 0 24px 0;">
      <h2 class="lg-text">Checkout</h2>
      <!-- Payment logic -->
      <div class="cart-form-lg">
        <%= render "charges/shared/payment_stripe", cart_items: @cart_items, order: @order, amount: @amount, description: @description %>
      </div>
    </div>
  </section>
</article>

app/views/charges/shared/_payment_stripe.html.erb
<section>
  <!-- Breakdown of cart items -->
  <%= render "charges/shared/display_orders", cart_items: cart_items, order: order %>
  <!-- Total pricing -->
  <label class="amount">
    <p>Subtotal: <span><%= pretty_amount(@amount) %></span></p>
  </label>
  <%= form_tag charges_path do %>
    <button type="submit" class="cta-btn-background">Checkout</button>
  <% end %>
  <!-- it is an <a> so it doesnt trigger Stripe checkout -->
  <button class="next-btn go-step-one a-link" data-key="two">Previous</button>
</section>