config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  resources :newsletters, only: [:create]
  resources :pages, only: [:index, :new, :create]
  resources :products, only: [:index, :show, :create] do
    resources :reviews, only: [:create, :update, :destroy ]
    member do
      post 'toggle_favorite', to: "products#toggle_favorite"
    end
  end

  resources :users, only: [:show, :update]
  resources :orders, only: [:update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create], path: 'cart'
  get 'success', to: 'charges#success_charge'
  get 'cancel', to: 'charges#cancel_charge'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-lw alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close" >
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-lw alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container top-footer-div">
  <div class="row py-4">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="" alt="" width="180" class="mb-3">
      <p class="font-italic text-grey">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
      <ul class="list-inline mt-4">
        <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fab fa-twitter"></i></a></li>
        <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fab fa-instagram"></i></a></li>
        <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fab fa-pinterest"></i></a></li>
      </ul>
    </div>
    <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
      <h6 class="text-uppercase mb-4">Company</h6>
      <ul class="list-unstyled mb-0">
        <li class="mb-2"><a href="/" class="text-grey">Home</a></li>
        <li class="mb-2"><a href="/about" class="text-grey">About</a></li>
        <li class="mb-2"><a href="/products" class="text-grey">Our Products</a></li>
      </ul>
    </div>
    <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
      <h6 class="text-uppercase mb-4">Others</h6>
      <ul class="list-unstyled mb-0">
        <li class="mb-2"><a href="#" class="text-grey">Services</a></li>
        <li class="mb-2"><a href="#" class="text-grey">Terms</a></li>
        <li class="mb-2"><a href="#" class="text-grey">Privacy Policy</a></li>
      </ul>
    </div>
    <div class="col-lg-4 col-md-6 mb-lg-0">
      <h6 class="text-uppercase mb-4">Newsletter</h6>
      <p class="text-grey mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. At itaque temporibus.</p>
      <div class="p-1 rounded border">
        <div class="input-group">
          <%= form_with url: "/newsletters", method: :puts do |form| %>
            <%= form.text_field :email, :class => 'input-newsletter' %>
            <div class="input-group-append">
              <button class="btn btn-link"><i class="fa fa-paper-plane"><%= form.submit "" %></i></button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Copyrights -->
<div class="py-4">
  <div class="container text-center">
    <p class="text-grey mb-0 py-2">© <%= Time.new.year %> <%= ENV['SHOP_NAME'] %> All rights reserved.</p>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= image_tag "logo.png", width: 60, alt: "logo"%></a>
    <button class="navbar-toggler btn-menu" type="button" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    </button>
    <div >
      <ul class="navbar-nav center-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="../">home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../products">catalog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../about">about</a>
        </li>
      </ul>
    </div>
    <div class="navbar-collapse closing-menu" >
      <a class="nav-link active" aria-current="page" href="../">home</a>
      <a class="nav-link" href="../products">catalog</a>
      <a class="nav-link" href="../about">about</a>
    </div>
    <div>
      <ul class="right-nav">
        <li>
          <%= form_tag products_path, class: "form-inline", method: :get do %>
            <%= text_field_tag :query,
            params[:query],
            class: "close-search",
            placeholder: "Search product"
          %>
            <button type="submit" id="search" class="search-btn"><i class="fas fa-search"></i></button>
          <% end %>
        </li>
        <li>
          <a class="nav-link cart-nav" href="../cart/new"><i class="fas fa-shopping-bag"></i></a>
          <% if current_user && current_user.orders.where(status: 1)[0] && current_user.orders.where(status: 1)[0].order_items.count > 0 %>
            <p class="items-cart"><%= current_user.orders.where(status: 1)[0].order_items.count %></p>
          <% end %>
        </li>
        <li>
          <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
              <li class="nav-item dropdown dropdown-nav">
                <%= image_tag "#{@user.icon.url}", class: "avatar dropdown-toggle", role: 'button', 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <ul class="avatar-ul">
                    <li class="nav-item active">
                      <%= link_to "Profile", "../users/#{current_user.id}", class: "dropdown-item" %>
                    </li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </ul>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link" do %>
                  <i class="fas fa-user-alt"></i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<script>
  if(document.querySelector(".dropdown-nav")) {
    document.querySelector(".dropdown-nav").addEventListener("click", (event) => {
      document.querySelector(".dropdown-menu-right").classList.toggle("dropdown-avatar-show")
    })
  }
</script>