config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  resources :newsletters, only: [:create]
  resources :pages, only: [:index, :new, :create]
  resources :products, only: [:index, :show, :create] do
    resources :reviews, only: [:create, :update, :destroy ]
    member do
      post 'toggle_favorite', to: "products#toggle_favorite"
    end
  end

  resources :users, only: [:show, :update]
  resources :orders, only: [:update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create], path: 'cart'
  get 'success', to: 'charges#success_charge'
  get 'cancel', to: 'charges#cancel_charge'
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ],
  using: {
    tsearch: { 
      prefix: true,
      highlight: {
        StartSel: '<b>',
        StopSel: '</b>',
        MaxWords: 123,
        MinWords: 456,
        ShortWord: 0,
        HighlightAll: true,
        MaxFragments: 3,
        FragmentDelimiter: '&hellip;'
      }
    }
  }

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :order_items, dependent: :destroy

  has_many_attached :photos
  
  acts_as_favoritable

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  # Availability: 1 available / 2 unavailable
  validates :availability, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 2 }

  before_validation :initial_sales, on: :create

  private 

  def self.order_list(sort_by)
    case sort_by
    when 'featured'
      self.order(sales: :desc)
    when 'name A-Z'
      self.order(:name)
    when 'name Z-A'
      self.order(name: :desc)
    when 'rating 1-5'
      self.order(:rating)
    when 'rating 5-1'
      self.order(rating: :desc)
    when 'price low-high'
      self.order(:price)
    when 'price high-low'
      self.order(price: :desc)
    when 'date old-new'
      self.order(:updated_at)
    when 'date new-old'
      self.order(updated_at: :desc)
    else 
      self.order(sales: :desc)
    end
  end
 
  def initial_sales
    self.sales = 0
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :index, :show ]

    def index
        @user = current_user
        if params[:query].present?
            @products_highlight = policy_scope(Product).search_by_name_and_description(params[:query]).with_pg_search_highlight
            @featured_products =Product.order(sales: :desc).first(3)
        else
            @products = policy_scope(Product.order_list(params[:sort_by]))
            @featured_products =Product.order(sales: :desc).first(3)
        end
    end

    def create
        @product = Product.new(product_params)
        if current_user.admin
            @user = current_user
            @product.user = @user
            authorize @product
            @product.save!
        else 
            redirect_to root_path
        end 
        redirect_to products_path
    end

    def show
        @product = Product.find(params[:id])
        @related_products = Product.order(rating: :desc).first(4)
        @reviews = @product.reviews
        @order_item = OrderItem.new
        @review = Review.new
        @admin = User.find_by(admin: true)
        if params[:user_id]
            @user = User.find(params[:user_id])
        else
            @user = current_user
        end
        authorize @product
    end

    def toggle_favorite
        @product = Product.find_by(id: params[:id])
        current_user.favorited?(@product) ? current_user.unfavorite(@product) : current_user.favorite(@product)
        authorize @product
        respond_to do |format|
            format.html { redirect_to request.referrer }
            format.js 
        end
    end

    private

    def product_params
        params.require(:product).permit(:name, :description, :price, :availability, photos: [])
    end
end

app/views/products/shared/_cart_product.html.erb
<% if current_user && order_item %>
  <%= form_for(order_item) do |form| %>
    <%= form.hidden_field :product_id, value: product.id %>
    <%= form.number_field :quantity, in: 1.0..20.0, step: 1, value: 1 %>
    <div class="buy-cta-btn-no-background">
      <%= form.submit "ADD TO CART", class: "add-to-cart" , style: "border: none !important; background: none; color: white; transition: all ease-in-out 0.35s;" %>
    </div>
  <% end %>
<% else %>
  <%= link_to new_user_session_path do %>
    <button class="buy-cta-btn-no-background cta-not-user">ADD TO CART</button>
  <% end %>
<% end %>

app/views/products/shared/_create_review.html.erb
<div class="tab-header">
  <h3>Customer reviews</h3>
</div>
<div class="d-flex justify-content-between separate-line align-items-baseline flex-wrap">
  <!-- Overall rating/reviews -->
  <div class="d-flex">
    <div style="width: 163px;">
      <% if product.rating %>
        <% product.rating.floor.times do %>
          <i class="fas fa-star active"></i>
        <%end %>
        <% if product.rating.to_s.include?('.5') %>
          <i class="fas fa-star-half-alt active"></i>
        <% end %>
        <% (5 - product.rating.ceil).times do %>
          <i class="fas fa-star"></i>
        <% end %>
      <% else %>
        <% 5.times do %>
          <i class="fas fa-star"></i>
          <p>No reviews</p>
        <% end %>
      <%end %>
    </div>
    <div class="mx-3 fst-italic reviews-number">
      <% if product.reviews.count == 0 %>
        <p>Be the first one to review it!</p>
      <% else %>
        <p>Based on <%= product.reviews.count %> reviews</p>
      <% end %>
    </div>
  </div>
  <!-- Write a review btn and logic -->
  <div>
    <% if user %>
      <!-- Button trigger modal -->
      <button type="button" class="modal-btn simple-btn" data-bs-toggle="modal" data-bs-target="#ReviewModalCenter" style="color: white">
        <span>Write a review</span>
        <div class="icon">
          <i class="fa pencil-icon"></i>
        </div>
      </button>
      <!-- Modal -->
      <div class="modal fade" id="ReviewModalCenter" tabindex="-1" role="dialog" aria-labelledby="ReviewModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">New review</h5>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= render "products/shared/create_review_modal", review: review, product: product %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to new_user_session_path do %>
        <button class="simple-btn">
          <span>Write a review</span>
          <div class="icon">
            <i class="fa pencil-icon"></i>
          </div>
        </button>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/shared/_display_product.html.erb
<% product.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>
<ul>
  <li><%= product.name %></li>
  <% if product.availability == 2%>
    <li>Unavailable</li>
  <%end %>
  <li><%= product.description %></li>
  <li>¥<%= product.price %></li>
  <div>
    <% if product.rating %>
      <% product.rating.floor.times do %>
        <i class="fas fa-star active"></i>
      <%end %>
      <% if product.rating.to_s.include?('.5') %>
        <i class="fas fa-star-half-alt active"></i>
      <% end %>
      <% (5 - product.rating.ceil).times do %>
        <i class="fas fa-star"></i>
      <% end %>
    <% else %>
      <% 5.times do %>
        <i class="fas fa-star"></i>
      <% end %>
    <%end %>
  </div>
</ul>

app/views/products/shared/_display_product_images.html.erb
<div class="main-pic">
</div>
<div class="image-flex">
  <% product.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, class: 'changeable-pic', style: "" %>
  <% end %>
</div>

app/views/products/shared/_display_product_info.html.erb
<ul class="product-info-list">
  <li>
    <h1><%= product.name %></h1>
  </li>
  <div>
    <% if product.rating %>
      <% product.rating.floor.times do %>
        <i class="fas fa-star active"></i>
      <%end %>
      <% if product.rating.to_s.include?('.5') %>
        <i class="fas fa-star-half-alt active"></i>
      <% end %>
      <% (5 - product.rating.ceil).times do %>
        <i class="fas fa-star"></i>
      <% end %>
    <% else %>
      <% 5.times do %>
        <i class="fas fa-star"></i>
        <p>No reviews</p>
      <% end %>
    <%end %>
  </div>
  <li>
    <p id="product-info-price"><%= pretty_amount(product.price) %></p>
  </li>
  <% if product.availability == 2%>
    <li>
      <p id="product-info-availability">Unavailable</p>
    </li>
  <%end %>
  <li>
    <p class="product-description"><%= product.description %></p>
  </li>
  <li>
    <ul class="list-inline mt-3 separate-line">
      <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fab fa-twitter"></i></a></li>
      <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fab fa-instagram"></i></a></li>
      <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fab fa-pinterest"></i></a></li>
    </ul>
  </li>
</ul>

app/views/products/shared/_display_products_wrapper.html.erb
<div class="wrapper-grid">
  <div class="wrapper-left">
    <!-- Filter products by stars/price -->
    <%= render "products/shared/filter_products" %>
    <!-- Featured products -->
    <%= render "products/shared/featured_products", featured_products: featured_products %>
  </div>
  <div class="right-side">
    <div class="order-products">
      <div class="dropdown">
        <button class="sort_drop">Sort by <i class="fas fa-caret-down"></i></button>
        <div class="made-dropdown-menu">
          <%= link_to "Best Selling", products_path(sort_by: 'featured'), class: 'dropdown-item' %>
          <%= link_to "Alphabetically, A to Z", products_path(sort_by: 'name A-Z'), class: 'dropdown-item' %>
          <%= link_to "Alphabetically, Z to A", products_path(sort_by: 'name Z-A'), class: 'dropdown-item' %>
          <%= link_to "Rating, low to high", products_path(sort_by: 'rating 1-5'), class: 'dropdown-item' %>
          <%= link_to "Rating, high to low", products_path(sort_by: 'rating 5-1'), class: 'dropdown-item' %>
          <%= link_to "Price, low to high", products_path(sort_by: 'price low-high'), class: 'dropdown-item' %>
          <%= link_to "Price, high to low", products_path(sort_by: 'price high-low'), class: 'dropdown-item' %>
          <%= link_to "Date, new to old", products_path(sort_by: 'date new-old'), class: 'dropdown-item' %>
          <%= link_to "Date, old to new", products_path(sort_by: 'date old-new'), class: 'dropdown-item' %>
        </div>
      </div>
    </div>
    <div class="wrapper-right">
      <!-- Products catalog -->
      <% if products_highlight %>
        <%= render "products/shared/highlight_products_catalog", products_highlight: products_highlight %>
      <% else %>
        <%= render "products/shared/products_catalog", products: products %>
      <% end %>
    </div>
    <!-- Pagination -->
    <div id="pagination-container" class="simple-pagination"></div>
  </div>
</div>

app/views/products/shared/_favorite_product.html.erb
<% if current_user %>
  <div class="separate-line mt-3" id="favoritor">
    <%= link_to toggle_favorite_product_path(product), class: "d-flex" , remote: true, method: :post, "data-id": "#{product.id}" do %>
      <%= render 'pages/like_button', product: product %>
      <p id="like-text">Add to wishlist</p>
    <% end %>
  </div>
<% else %>
  <div class="separate-line">
  </div>
<% end %>

app/views/products/shared/_featured_products.html.erb
<button class="accordion">Featured products</button>
<div class="filter-div hidden-filter-div">
  <h2>BEST SELLER</h2>
  <div class="flex-featured">
    <% featured_products.each do |product| %>
      <div class="featured-card">
        <%= link_to product_path(product) do %>
        <% end %>
        <%= cl_image_tag product.photos[0].key, height: 300, width: 400, crop: :fill, class: 'featured-product-pic' %>
        <div class="featured-info">
          <h3><%= product.name %></h3>
          <div>
            <% if product.rating %>
              <% product.rating.floor.times do %>
                <i class="fas fa-star active"></i>
              <%end %>
              <% if product.rating.to_s.include?('.5') %>
                <i class="fas fa-star-half-alt active"></i>
              <% end %>
              <% (5 - product.rating.ceil).times do %>
                <i class="fas fa-star"></i>
              <% end %>
            <% else %>
              <% 5.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            <%end %>
          </div>
          <p><%= pretty_amount(product.price) %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/shared/_filter_products.html.erb
<button class="accordion">Filter products</button>
<div class="filter-div hidden-filter-div">
  <div>
    <h2>CATALOG</h2>
    <h3>Price</h3>
    <ul>
      <li class="price-filter" data-minprice=0 data-maxprice=999>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        Less than ¥1000
      </li>
      <li class="price-filter" data-minprice=1000 data-maxprice=2000>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        ¥1000 - ¥2000
      </li>
      <li class="price-filter" data-minprice=2001 data-maxprice=3000>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        ¥2000 - ¥3000
      </li>
      <li class="price-filter" data-minprice=3001 data-maxprice=4000>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        ¥3000 - ¥4000
      </li>
      <li class="price-filter" data-minprice=4001 data-maxprice=5000>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        ¥4000 - ¥5000
      </li>
      <li class="price-filter" data-minprice=5001 data-maxprice=999999>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        More than ¥5000
      </li>
    </ul>
  </div>
  <div>
    <h3>Stars</h3>
    <ul>
      <li class="stars-filter" data-stars=0.0>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        <div>
          <% 5.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
      </li>
      <li class="stars-filter" data-stars=1.0>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        <div>
          <i class="fas fa-star active"></i>
          <% 4.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
      </li>
      <li class="stars-filter" data-stars=2.0>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        <div>
          <% 2.times do %>
            <i class="fas fa-star active"></i>
          <% end %>
          <% 3.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
      </li>
      <li class="stars-filter" data-stars=3.0>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        <div>
          <% 3.times do %>
            <i class="fas fa-star active"></i>
          <% end %>
          <% 2.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
      </li>
      <li class="stars-filter" data-stars=4.0>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        <div>
          <% 4.times do %>
            <i class="fas fa-star active"></i>
          <% end %>
          <i class="fas fa-star"></i>
        </div>
      </li>
      <li class="stars-filter" data-stars=5.0>
        <p class="tick check-box hidden">☑</p>
        <p class="check-box box">☐</p>
        <div>
          <% 5.times do %>
            <i class="fas fa-star active"></i>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/products/shared/_highlight_products_catalog.html.erb
<% products_highlight.each do |product| %>
  <div class="mini-product-card active" data-price=<%= product.price %> data-stars=<%= product.rating %>>
    <%= link_to product_path(product) do %>
    <% end %>
    <div class="info-hover">
      <a href="/products/<%= product.id %>"><i class="fas fa-eye"></i></a>
      <!-- Favoritor -->
      <%= render "pages/shared/favoritor", product: product  %>
      <!-- Cart icon -->
      <%= render "pages/shared/cart_display", product: product %>
    </div>
    <%= cl_image_tag product.photos[0].key, height: 300, width: 400, crop: :fill, class: 'product-first-pic' %>
    <%= cl_image_tag product.photos[2].key, height: 300, width: 400, crop: :fill, class: 'product-second-pic' %>
    <div class="product-info">
      <!-- [NOT USED FOR NOW - MAYBE IT IS TOO MUCH TO HIGHLIGHT] 
      If the title is in the highlight, it will show the title hightlighted in the card, if not, the normal title 
      <% if !product.pg_search_highlight.split[0...product.name.split.size].join(" ").gsub(/<\/?b>/, "").include?(product.name)  %>
        <h3><%= product.name %></h3>
      <% else %>
        <h3><%= "#{product.pg_search_highlight.split[0...product.name.split.size].join(" ")}".html_safe%></h3>
      <% end %>
      <p><%= "#{product.pg_search_highlight.split[product.name.split.size..-1].join(" ")}".html_safe %></p>
      -->
      <h3><%= product.name %></h3>
      <div>
        <% if product.rating %>
          <% product.rating.floor.times do %>
            <i class="fas fa-star active"></i>
          <%end %>
          <% if product.rating.to_s.include?('.5') %>
            <i class="fas fa-star-half-alt active"></i>
          <% end %>
          <% (5 - product.rating.ceil).times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <% else %>
          <% 5.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <%end %>
      </div>
      <p><%= pretty_amount(product.price) %></p>
    </div>
  </div>
<% end %>

app/views/products/shared/_products_catalog.html.erb
<% products.each do |product| %>
  <div class="mini-product-card active" data-price=<%= product.price %> data-stars=<%= product.rating %>>
    <%= link_to product_path(product) do %>
    <% end %>
    <div class="info-hover">
      <a href="/products/<%= product.id %>"><i class="fas fa-eye"></i></a>
      <!-- Favoritor -->
      <%= render "pages/shared/favoritor", product: product  %>
      <!-- Cart icon -->
      <%= render "pages/shared/cart_display", product: product %>
    </div>
    <%= cl_image_tag product.photos[0].key, height: 300, width: 400, crop: :fill, class: 'product-first-pic' %>
    <%= cl_image_tag product.photos[2].key, height: 300, width: 400, crop: :fill, class: 'product-second-pic' %>
    <div class="product-info">
      <h3><%= product.name %></h3>
      <div>
        <% if product.rating %>
          <% product.rating.floor.times do %>
            <i class="fas fa-star active"></i>
          <%end %>
          <% if product.rating.to_s.include?('.5') %>
            <i class="fas fa-star-half-alt active"></i>
          <% end %>
          <% (5 - product.rating.ceil).times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <% else %>
          <% 5.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <%end %>
      </div>
      <p><%= pretty_amount(product.price) %></p>
    </div>
  </div>
<% end %>

app/views/products/shared/_related_products_catalog.html.erb
<% related_products.each do |product| %>
  <div class="mini-product-card active" data-price=<%= product.price %> data-stars=<%= product.rating %>>
    <%= link_to product_path(product) do %>
    <% end %>
    <div class="info-hover">
      <a href="/products/<%= product.id %>"><i class="fas fa-eye"></i></a>
      <!-- Favoritor -->
      <%= render "pages/shared/favoritor", product: product  %>
      <!-- Cart icon -->
      <%= render "pages/shared/cart_display", product: product %>
    </div>
    <%= cl_image_tag product.photos[0].key, height: 300, width: 400, crop: :fill, class: 'product-first-pic' %>
    <%= cl_image_tag product.photos[2].key, height: 300, width: 400, crop: :fill, class: 'product-second-pic' %>
    <div class="product-info">
      <h3><%= product.name %></h3>
      <div>
        <% if product.rating %>
          <% product.rating.floor.times do %>
            <i class="fas fa-star active"></i>
          <%end %>
          <% if product.rating.to_s.include?('.5') %>
            <i class="fas fa-star-half-alt active"></i>
          <% end %>
          <% (5 - product.rating.ceil).times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <% else %>
          <% 5.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <%end %>
      </div>
      <p><%= pretty_amount(product.price) %></p>
    </div>
  </div>
<% end %>

app/views/products/shared/_render_review.html.erb
<div class="display-reviews">
  <% if reviews %>
    <% reviews.each do |review| %>
      <ul class="separate-line">
        <li><% if review.rating %>
            <% review.rating.floor.times do %>
              <i class="fas fa-star active"></i>
            <%end %>
            <% if review.rating.to_s.include?('.5') %>
              <i class="fas fa-star-half-alt active"></i>
            <% end %>
            <% (5 - review.rating.ceil).times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <% else %>
            <% 5.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <%end %></li>
        <li class="review-title"><%= review.title %></li>
        <li class="review-date"><%= review.user.username %> on <%= review.updated_at.strftime('%b %e, %Y') %></li>
        <li class="review-content"><%= review.content %></li>
        <!-- Delete button -->
        <% if review.user == user || current_user == admin %>
          <li class="review-delete"><%= link_to "Delete", product_review_path(product, review), method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% end %>
      </ul>
      <!-- Toggleable Edit Form -->
      <%# if review.user == user || current_user == admin %>
      <%# <button>Edit the review</button> %>
      <%# <div> %>
      <%# simple_form_for([@product, review], remote: true, method: :patch) do |f| %>
        <%# f.input :rating %>
        <%# f.input :title %>
        <%# f.input :content, as: :text %>
        <%# f.submit %>
        <%# end %>
        <%# </div> %>
        <!-- Delete button -->
        <%#= link_to "Delete review", product_review_path(product, review), method: :delete, data: { confirm: "Are you sure?" } %>
        <%#end %>
      <% end %>
    <% end %>
  </div>

app/views/products/shared/_search_query.html.erb
<% products_highlight.each do |product| %>
  <%= link_to product_path(product) do %>
    <ul>
      <li><%= "#{product.pg_search_highlight.split[0...product.name.split.size].join(" ")}".html_safe%></li>
      <li><%= "#{product.pg_search_highlight.split[product.name.split.size..-1].join(" ")}".html_safe %></li>
      <li><%= pretty_amount(product.price) %></li>
      <li><%= product.rating %></li>
    </ul>
  <% end %>
<% end %>